'use client'

import { cards } from '@/helpers/cards'
import { Card } from '@/interfaces/card'
import { Inter } from 'next/font/google'
import { createContext, useState } from 'react'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const BoardContext = createContext<{
  boardCards: Card[]
  addCard: (card: Card) => void
}>({ boardCards: [], addCard: () => {} })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const [stateCards, setStateCards] = useState(cards.slice(3))
  const addCardToBoard = (card: Card) => {
    setStateCards((prevCards) => [...prevCards, card])
  }

  return (
    <BoardContext.Provider
      value={{
        boardCards: stateCards,
        addCard: (card) => addCardToBoard(card),
      }}
    >
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </BoardContext.Provider>
  )
}
